name: github-actions-workflow
on:
  push:
    branches:
      - 'main'
      - 'master'
      - github-custom-composite-actions
env:
  WORKFLOW_ENV_1: ${{ secrets.WORKFLOW_ENV_1 }}
  WORKFLOW_ENV_2: ${{ secrets.WORKFLOW_ENV_2 }}
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [23, 24]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env: 
      TEST_ENV_1: "Hello Test Env 1."
      TEST_ENV_2: "Thank you. BYE."
    steps:
      - name: Get the code.
        uses: actions/checkout@v5
      - name: Using Customized Composite Actions for Caching.
        uses: ./github/actions/cached-deps/composite-action.yml
      - name: Test the code.
        run: npm run test
      - name: Finish Test.
        run: echo "All the process under the Test job is successfully completed!"
      - name: Test Workflow Environment Variable.
        run: echo "$WORKFLOW_ENV_1" and "$WORKFLOW_ENV_2"
      - name: Test Job level Environment Variable.
        run: echo "${{env.TEST_ENV_1}}" and "${{env.TEST_ENV_2}}"
      - name: Test Step level Environment Variable.
        env:
          STEP_ENV: 'Step env variable'
        run: echo "$STEP_ENV"
  build:
    needs: test
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
        node-version: [23, 24]
    runs-on: ${{ matrix.operating-system }}
    outputs:
      build_job_output: ${{ steps.test_job_step.outputs.build_job_output }}
    steps:
      - id: test_job_step
        run: echo "my_output_name=build" >> "$GITHUB_OUTPUT"
      - name: Get the code.
        uses: actions/checkout@v5
      - name: Install Latest Version of NODE.
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Using Customized Composite Actions for Caching.
        uses: ./github/actions/cached-deps/composite-action.yml
      - name: Build the code. 
        run: NODE_OPTIONS=--openssl-legacy-provider npm run build
      - name: Publish the JS filename
        # run: find dist/static/*.js -type f -execdir echo 'build_job_output={}' >> $GITHUB_OUTPUT ';'
        run: find build/static/js -type f -name "*.js" -print0 | xargs -0 echo "build_job_output=$(cat)" >> "$GITHUB_OUTPUT"
      - name: Upload the job artifacts of the project build.
        uses: actions/upload-artifact@v4
        with:
          name: expense-calculator-build-job-artifacts-${{ matrix.operating-system }}-${{ matrix.node-version }}
          path: 
            build
      - name: Verify the files in the dist path
        run: ls
  deploy:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [23, 24]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download the job artifacts of the project build.
        uses: actions/upload-artifact@v4
        with:
          name: expense-calculator-deploy-job-artifacts-${{ matrix.operating-system }}-${{ matrix.node-version }}
          path:
            build
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hiddeb-files: false
      - name: Output Contents
        run: ls
      - name: Output contents from the build job.
        run: echo "${{ needs.build.outputs.build_job_output }}"
      - name: Get the code.
        uses: actions/checkout@v5
      - name: Install Latest Version of NODE.
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Using Customized Composite Actions for Caching.
        uses: ./github/actions/cached-deps/composite-action.yml
      - name: Build the code. 
        run: NODE_OPTIONS=--openssl-legacy-provider npm run build
      - name: Deploy the application to the server.
        run: echo "Deployment Successfully Completed."
